# Generated by Django 3.0.8 on 2020-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField()),
            ],
        ),
    ]
