# Generated by Django 3.0.8 on 2020-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200803_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
