# Generated by Django 3.0.9 on 2020-08-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('uc', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('tipo', models.CharField(max_length=9)),
                ('ht', models.FloatField(default=0)),
                ('hp', models.FloatField(blank=True, default=0, null=True)),
                ('hl', models.FloatField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('fk_sholl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.School', verbose_name='School')),
            ],
        ),
    ]
