# Generated by Django 3.0.9 on 2020-08-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='fk_sholl',
            new_name='fk_shool',
        ),
    ]
