# Generated by Django 3.0.9 on 2020-08-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20200803_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='fk_shool',
            new_name='fk_school',
        ),
    ]
