# Generated by Django 3.0.9 on 2020-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20200803_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
