# Generated by Django 3.0.8 on 2020-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='DNI',
            new_name='dni',
        ),
    ]
