# Generated by Django 3.0.8 on 2020-08-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20200803_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
