# Generated by Django 3.0.9 on 2020-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20200803_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
