# Generated by Django 3.0.9 on 2020-08-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20200803_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=8)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('created_date', models.DateTimeField(blank=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('fk_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Person', verbose_name='Person')),
                ('fk_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Section', verbose_name='Section')),
            ],
        ),
    ]
