# Generated by Django 3.0.8 on 2020-08-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_register', to='rest.Section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sections',
            field=models.ManyToManyField(through='rest.Enrollment', to='rest.Section'),
        ),
    ]
