# Generated by Django 3.0.8 on 2020-08-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_auto_20200804_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sections',
            field=models.ManyToManyField(through='rest.Enrollment', to='rest.Section'),
        ),
    ]
