# Generated by Django 3.0.8 on 2020-08-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20200804_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='register',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sections',
        ),
    ]
